[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.54.1"
aws-sdk-kinesis = "0.24.0"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
base64 = "0.13.1"
flate2 = "1.0.25"
clap = { version = "4.1.4", features = ["derive"] }
