[package]
name = "ktr"
version = "0.1.0"
edition = "2021"
description = "KTR (Kinesis Tools Rust) allow to read aws kinesis streams"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.54.1"
aws-sdk-kinesis = "0.24.0"
tokio = { version = "1", features = ["sync", "rt", "macros", "rt-multi-thread"] }
dotenv = "0.15.0"
base64 = "0.21.0"
flate2 = "1.0.25"
clap = { version = "4.1.4", features = ["derive"] }
serde_json = "1.0.93"
