name: Build and Release

on:
  release:
    types: prereleased
  workflow_dispatch:

jobs:
  release-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - arch: 64-bit Linux
            target: x86_64-unknown-linux-gnu
          - arch: 32-bit Linux
            target: i686-unknown-linux-gnu
          - arch: ARM64 Linux
            target: aarch64-unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++-multilib g++-mingw-w64-x86-64
          rustup target add ${{ matrix.platform.target }}
      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ktr
          shared-key: ubuntu-latest
      - name: Build for Linux
        run: |
          cargo build --target=${{ matrix.platform.target }} --release
          mv target/${{ matrix.platform.target }}/release/ktr target/${{ matrix.platform.target }}/release/ktr-${{ matrix.platform.target }}
      - name: Release Linux builds
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.platform.target }}/release/${{ matrix.platform.target }}
          draft: true

  release-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - arch: 64-bit macOS
            target: x86_64-apple-darwin
          - arch: ARM64 macOS
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ktr
          shared-key: macos-latest
      - name: Build for Mac
        run: |
          cargo build --target ${{ matrix.platform.target }} --release
          mv target/${{ matrix.platform.target }}/release/ktr target/${{ matrix.platform.target }}/release/ktr-${{ matrix.platform.target }}
      - name: Release Mac builds
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.platform.target }}/release/${{ matrix.platform.target }}
          draft: true

  release-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - arch: 64-bit MSVC
            target: x86_64-pc-windows-msvc
          - arch: 32-bit MSVC
            target: i686-pc-windows-msvc
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ktr
          shared-key: windows-latest
      - name: Build for Windows
        run: |
          cargo build --target ${{ matrix.platform.target }} --release
          mv target/${{ matrix.platform.target }}/release/ktr.exe target/${{ matrix.platform.target }}/release/ktr-${{ matrix.platform.target }}.exe
      - name: Release Windows builds
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.platform.target }}/release/${{ matrix.platform.target }}.exe
          draft: true
