name: Build and Release

on:
  release:
    types: prereleased

jobs:
  release-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++-multilib g++-mingw-w64-x86-64
          rustup target add i686-unknown-linux-gnu
          rustup target add x86_64-unknown-linux-gnu

      - name: Build for 32-bit Linux
        run: |
          cargo build --target=i686-unknown-linux-gnu --release
          mv target/i686-unknown-linux-gnu/release/ktr target/i686-unknown-linux-gnu/release/ktr-i686-linux-gnu

      - name: Upload 32-bit Linux build
        uses: actions/upload-artifact@v3
        with:
          name: ktr-i686-linux-gnu
          path: target/i686-unknown-linux-gnu/release/ktr-i686-linux-gnu
          if-no-files-found: error

      - name: Build for 64-bit Linux
        run: |
          cargo build --target=x86_64-unknown-linux-gnu --release
          mv target/x86_64-unknown-linux-gnu/release/ktr target/x86_64-unknown-linux-gnu/release/ktr-x86_64-linux-gnu

      - name: Upload 64-bit Linux build
        uses: actions/upload-artifact@v3
        with:
          name: ktr-x86_64-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/ktr-x86_64-linux-gnu
          if-no-files-found: error

  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          default: true

      - name: Build for 64-bit Mac
        run: |
          cargo build --target x86_64-apple-darwin --release
          mv target/x86_64-apple-darwin/release/ktr target/x86_64-apple-darwin/release/ktr-x86_64-apple-darwin

      - name: Upload 64-bit Mac build
        uses: actions/upload-artifact@v3
        with:
          name: ktr-x86_64-apple-darwin
          path: target/x86_64-apple-darwin/release/ktr-x86_64-apple-darwin
          if-no-files-found: error

  release-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - arch: x64
            target: x86_64-pc-windows-msvc
          - arch: x86
            target: i686-pc-windows-msvc
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          default: true

      - name: Build for Windows
        run: |
          cargo build --target ${{ matrix.platform.target }} --release
          mv target/${{ matrix.platform.target }}/release/ktr target/${{ matrix.platform.target }}/release/ktr-${{ matrix.platform.target }}

      - name: Upload Windows builds
        uses: actions/upload-artifact@v3
        with:
          name: ktr-${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/ktr-${{ matrix.platform.target }}
          if-no-files-found: error

  release-all:
    name: Release all artifacts
    runs-on: ubuntu-latest
    needs: [ release-macos, release-linux ]
    steps:
      - run: mkdir -p releases
      - uses: actions/download-artifact@master
        with:
          name: ktr-i686-linux-gnu
          path: releases
      - uses: actions/download-artifact@master
        with:
          name: ktr-x86_64-linux-gnu
          path: releases
      - uses: actions/download-artifact@master
        with:
          name: ktr-x86_64-apple-darwin
          path: releases

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/ktr-i686-linux-gnu
            releases/ktr-x86_64-linux-gnu
            releases/ktr-x86_64-apple-darwin
          draft: true
