name: Build and Release

on:
  release:
    types: [created]

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++-multilib
          rustup target add i686-unknown-linux-gnu
          rustup target add x86_64-unknown-linux-gnu
          rustup target add aarch64-unknown-linux-gnu

      - name: Build for ARM64 Linux
        run: |
          cargo build --target=aarch64-unknown-linux-gnu --release
          mv target/aarch64-unknown-linux-gnu/release/ktr target/aarch64-unknown-linux-gnu/release/ktr-aarch64-linux

      - name: Upload ARM64 Linux build
        uses: actions/upload-artifact@v3
        with:
          name: ktr-aarch64-linux
          path: target/aarch64-unknown-linux-gnu/release/ktr-aarch64-linux

  release-all:
    name: Release all artifacts
    runs-on: ubuntu-latest
    needs: [ release-macos, release-linux ]
    steps:
      - run: mkdir -p releases
      - uses: actions/download-artifact@master
        with:
          name: ktr-aarch64-linux
          path: releases

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/ktr-aarch64-linux
          draft: true

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref }}" releases/ktr-aarch64-linux
